[pytest]
addopts = -v --alluredir=allure-results --html=report.html --self-contained-html --reruns 4 --reruns-delay 5
testpaths = tests
log_cli = true
log_cli_level = INFO
log_file = logs/pytest.log
log_file_level = DEBUG
